spring:
  application:
    name: savify-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/Savify
    username: '${DATABASE_USERNAME}'
    password: '${DATABASE_PASSWORD}'
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true